version: '3'

services: 
    www:
        build: .
        ports: 
            - 8000:80
        volumes: 
            - ./www:/var/www/html
        networks: 
            - default
        links: 
            - db
    db:
        image: mysql
        ports: 
            - 3306:3306
        environment: 
            MYAQL_DATABASE: myDB
            MYSQL_ROOT_PASSWORD: test
        networks: 
            - default